version: '3.1'
services:
  db:
    network_mode: host
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    network_mode: host
    image: "registry.mdcatapult.io/informatics/software-engineering/coshh"

