version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    image: "registry.mdcatapult.io/informatics/software-engineering/coshh:latest"
    ports:
      - "8080:8080"
